name: Env Priority

on:
    push:
env:
  VAR_EXAMPLE: workflow-level 
jobs:
    test_env:
        runs-on: ubuntu-latest
        env:
          VAR_EXAMPLE: job-level   
    
        steps:
            - name: step 1
              run: echo " Step 1 value: $VAR_EXAMPLE "
        
            - name: step 2
              env:
                VAR_EXAMPLE: step-level
              run: echo " Step 2 value: $VAR_EXAMPLE "
