name: External Trigger Workflow
on:
    repository_dispatch: 
        types:
            - custom-event

jobs:
  external:
    runs-on: ubuntu-latest
    steps:
      - name: print trigger source
        run: echo "Workflow triggered by external repository_dispatch event"
      
      - name: Print payload value
        run: echo "payload value.. ${{ github.event.client_payload.my_key }} "  

    